In [2]:
import pandas as pd

In [3]:
#filename and location of csv
csvfile1 = ('resources/FEWS.csv')

#not used
# csvfile2 = ('resources/light-duty-vehicles-2020-08-29.csv')

In [4]:
#csv to df
df1 = pd.read_csv(csvfile1)
#checkpoint
df1

/Users/aleciagraham/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42610,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
42611,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
42612,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
42613,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
42614,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [5]:
#get columns
df1.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb'],
      dtype='object')

In [6]:
#drop unneeded columns for fuel type1 table
df1_fuel=df1.drop(['displ','feScore', 'ghgScore','ghgScoreA', 'highway08','highwayA08', 
                   'hlv', 'hpv', 'lv2', 'lv4', 'phevBlended', 'pv2', 'pv4', 'guzzler',
                   'trans_dscr','createdOn', 'modifiedOn', 'startStop' , 'co2', 'co2A', 
                   'city08', 'cityA08', 'comb08','combA08', 'UCity', 'UCityA', 
                   'UHighway', 'UHighwayA', 'tCharger', 'sCharger','VClass','mpgData','mfrCode'], axis=1)

In [7]:
#determine different fuel types, to split into tables
# df1_fuel['fuelType'].unique()

In [8]:
#new columns
df1_fuel.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08U',
       'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2TailpipeAGpm',
       'co2TailpipeGpm', 'comb08U', 'combA08U', 'combE', 'combinedCD',
       'combinedUF', 'cylinders', 'drive', 'engId', 'eng_dscr', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'highway08U', 'highwayA08U',
       'highwayCD', 'highwayE', 'highwayUF', 'id', 'make', 'model', 'range',
       'rangeCity', 'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'year',
       'youSaveSpend', 'atvType', 'fuelType2', 'rangeA', 'evMotor', 'c240Dscr',
       'charge240b', 'c240bDscr', 'phevCity', 'phevHwy', 'phevComb'],
      dtype='object')

In [9]:
#reorder columns
df1_reorder = df1_fuel[['id', 'make', 'model', 'year', 'atvType', 
                        'trany', 
                        ##petroleum
                        'fuelType', 'fuelType1', 'fuelType2',
                        'fuelCost08', 'fuelCostA08', 
                        'barrels08', 'barrelsA08', 
                        ##petroleum measurements
                        'city08U', 'cityA08U', 
                        'highway08U', 'highwayA08U',
                        'comb08U', 'combA08U',
                        'cityCD', 'cityE', 'cityUF',
                        'highwayCD', 'highwayE', 'highwayUF',
                        'combinedCD', 'combE', 'combinedUF',
                        'co2TailpipeAGpm', 'co2TailpipeGpm', 
                        'cylinders', 'drive', 'engId', 'eng_dscr',
                         ##electric
                        'evMotor',
                        'charge120', 'c240Dscr',  'charge240', 
                        'c240bDscr', 'charge240b',
                        ##electric measurements
                        'range','rangeA', 
                        'rangeCity', 'rangeCityA', 
                        'rangeHwy', 'rangeHwyA', 
                        'phevCity', 'phevHwy', 
                        'phevComb',
                        ##evaluation
                        'youSaveSpend'
                       ]
                      ]

In [10]:
#make the slice a df
df_prep = pd.DataFrame(df1_reorder)

In [11]:
##renaming columns, friendly names, from documentation
df_prep.rename(columns ={'atvType':'advancement_type', 
                        'trany':'transmission',
                        ##petroleum
                        'fuelType':'fuel_types', 'fuelType1':'fuel1', 'fuelType2':'fuel2',
                        'fuelCost08':'fuel1_cost', 'fuelCostA08':'fuel2_cost', 
                        'barrels08': 'fuel1_consumption', 'barrelsA08':'fuel2_consumption', 
                        ##petroleum measurements
                        'city08U': 'fuel1_city_MPG', 'cityA08U':'fuel2_city_MPG', 
                        'highway08U':'fuel1_highway_MPG', 'highwayA08U':'fuel2_highway_MPG',
                        'comb08U': 'fuel1_combined_MPG', 'combA08U': 'fuel2_combined_MPG',
                        'cityCD':'city_CD', 'cityE':'city_E', 'cityUF':'city_UF',
                        'highwayCD':'highway_CD', 'highwayE':'highway_E', 'highwayUF':'highway_UF',
                        'combinedCD':'combined_CD', 'combE': 'combined_E', 'combinedUF':'combined_UF',
                        'co2TailpipeAGpm':'fuel1_co2_GPM', 'co2TailpipeGpm':'fuel2_co2_GPM', 
                        'drive':'drive_axel', 'engId':'engine_ID', 'eng_dscr':'engine_dscr',
                         ##electric
                        'evMotor':'electric_motor', 
                        'charge120':'charge_120v', 'c240Dscr':'charger_dscr','charge240': 'charge_240v', 
                        'c240bDscr':'alternate_charger_dscr','charge240b':'alternate_charger_240v',
                        ##electric measurements
                        'range':'fuel1_range','rangeA':'fuel2_range', 
                        'rangeCity':'fuel1_city_MPG', 'rangeCityA':'fuel2_city_MPG', 
                        'rangeHwy':'fuel1_highway_MPG', 'rangeHwyA':'fuel2_city_MPG', 
                        'phevCity':'hybrid_city_MPG', 'phevHwy':'hybrid_highway_MPG', 
                        'phevComb':'hybrid_combined_MPG',
                        ##evaluation
                        'youSaveSpend': 'save_to_spend'
                       }, inplace=True)

In [12]:
#check and rename
df2 = df_prep
df2

,id,make,model,year,advancement_type,transmission,fuel_types,fuel1,fuel2,fuel1_cost,...,fuel1_range,fuel2_range,fuel1_city_MPG,fuel2_city_MPG,fuel1_highway_MPG,fuel2_city_MPG,hybrid_city_MPG,hybrid_highway_MPG,hybrid_combined_MPG,save_to_spend
0,1,Alfa Romeo,Spider Veloce 2000,1985,NaN,Manual 5-spd,Regular,Regular Gasoline,NaN,1550,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-1750
1,10,Ferrari,Testarossa,1985,NaN,Manual 5-spd,Regular,Regular Gasoline,NaN,2950,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-8750
2,100,Dodge,Charger,1985,NaN,Manual 5-spd,Regular,Regular Gasoline,NaN,1200,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,0
3,1000,Dodge,B150/B250 Wagon 2WD,1985,NaN,Automatic 3-spd,Regular,Regular Gasoline,NaN,2950,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-8750
4,10000,Subaru,Legacy AWD Turbo,1993,NaN,Manual 5-spd,Premium,Premium Gasoline,NaN,2250,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-5250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42610,9995,Subaru,Legacy,1993,NaN,Automatic 4-spd,Regular,Regular Gasoline,NaN,1500,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-1500
42611,9996,Subaru,Legacy,1993,NaN,Manual 5-spd,Regular,Regular Gasoline,NaN,1400,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-1000
42612,9997,Subaru,Legacy AWD,1993,NaN,Automatic 4-spd,Regular,Regular Gasoline,NaN,1550,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-1750
42613,9998,Subaru,Legacy AWD,1993,NaN,Manual 5-spd,Regular,Regular Gasoline,NaN,1550,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-1750
42614,9999,Subaru,Legacy AWD Turbo,1993,NaN,Automatic 4-spd,Premium,Premium Gasoline,NaN,2350,...,0,NaN,0.0,0.0,0.0,0.0,0,0,0,-5750

In [13]:
#filter out cars made before year 2000
df_ev = df2[df2['year'] >= 2000]

In [14]:
#checkpoint
df_ev

,id,make,model,year,advancement_type,transmission,fuel_types,fuel1,fuel2,fuel1_cost,...,fuel1_range,fuel2_range,fuel1_city_MPG,fuel2_city_MPG,fuel1_highway_MPG,fuel2_city_MPG,hybrid_city_MPG,hybrid_highway_MPG,hybrid_combined_MPG,save_to_spend
6210,15589,Acura,NSX,2000,NaN,Automatic 4-spd,Premium,Premium Gasoline,NaN,2350,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-5750
6212,15590,Acura,NSX,2000,NaN,Manual 6-spd,Premium,Premium Gasoline,NaN,2350,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-5750
6213,15591,BMW,M Coupe,2000,NaN,Manual 5-spd,Premium,Premium Gasoline,NaN,2250,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-5250
6214,15592,BMW,Z3 Coupe,2000,NaN,Automatic 4-spd,Premium,Premium Gasoline,NaN,2250,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-5250
6215,15593,BMW,Z3 Coupe,2000,NaN,Manual 5-spd,Premium,Premium Gasoline,NaN,2250,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-5250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36277,42982,Toyota,4Runner 4WD,2021,NaN,Automatic (S5),Regular,Regular Gasoline,NaN,1900,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-3500
36278,42983,Honda,Clarity,2021,Plug-in Hybrid,Automatic (variable gear ratios),Regular Gas and Electricity,Regular Gasoline,Electricity,800,...,0,48,0.0,50.78,0.0,44.13,82,70,76,2750
36279,42984,Volvo,S90 AWD PHEV,2021,Plug-in Hybrid,Automatic (S8),Premium and Electricity,Premium Gasoline,Electricity,1400,...,0,21,0.0,21.51,0.0,21.34,38,42,40,-250
36280,42985,Volvo,V60 AWD PHEV,2021,Plug-in Hybrid,Automatic (S8),Premium and Electricity,Premium Gasoline,Electricity,1400,...,0,22,0.0,22.40,0.0,22.08,40,44,42,250
36281,42986,Chrysler,Pacifica AWD,2020,NaN,Automatic 9-spd,Regular,Regular Gasoline,NaN,1650,...,0,NaN,0.0,0.00,0.0,0.00,0,0,0,-2250

In [15]:
df_ev.to_csv('resources/cars.csv')